# Generated by Django 5.0.3 on 2024-03-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='recipe',
        ),
        migrations.AddField(
            model_name='favorite',
            name='recipe',
            field=models.ManyToManyField(to='Cooking.recipe'),
        ),
    ]
