# Generated by Django 5.0.3 on 2024-03-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cooking', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
    ]
