# Generated by Django 5.0.3 on 2024-03-29 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooking', '0004_remove_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Medium'), (4, 'Difficult'), (5, 'Very Difficult')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Difficulty'),
            preserve_default=False,
        ),
    ]
